### PR TITLE
HF02-Hot fix 02

### PR DESCRIPTION
**Pull request by liemnv60cntt**
- Add BrandId attribute into Product table
- Update database and data
- Edit Create Product API
- Edit Update Product API
- Edit Get Product List API
- Add Get Brand By Id API
- Add Get Category By Id API
- Rename ProductController, UserController to ProductsController, UsersController

### CODE REVIEW

**Comment by NguyenHuyGit** [comment]
Good job, Liem.

**Comment by taidora03999** [comment]
Well done, good job everyone.

**Comment by vodinhchi** [comment]
Wowww...
That’s a good effort...

**Comment by Nguyenvanhung270** [comment]
okay

**Comment by Nguyenvanhung270** [comment]
Nice

**Pull request merged**
